#!/bin/sh

set -u # Treat unset variables as an error.

if ! check_pid_namespace >/dev/null; then
    printf "%s\n" "--no-sandbox"
fi

printf "%s\n" "--disable-dev-shm-usage"
printf "%s\n" "--ignore-gpu-blocklist"
printf "%s\n" "--simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'"
printf "%s\n" "--start-maximized"
printf "%s\n" "--user-data-dir=/config/chromium"

# Anti-detection: suppress automation signals
printf "%s\n" "--disable-blink-features=AutomationControlled"
printf "%s\n" "--disable-features=EnableAutomation"
printf "%s\n" "--disable-infobars"

# Enable Chrome DevTools Protocol for remote debugging and agent-browser --cdp
# Bound to 0.0.0.0 for container network access (CDP rejects non-localhost by default)
printf "%s\n" "--remote-debugging-port=9222"
printf "%s\n" "--remote-debugging-address=0.0.0.0"
printf "%s\n" "--remote-allow-origins=*"

# Proxy support (set CHROMIUM_PROXY_SERVER env var to enable)
if [ -n "${CHROMIUM_PROXY_SERVER:-}" ]; then
    printf "%s\n" "--proxy-server=$CHROMIUM_PROXY_SERVER"
    printf "%s\n" "--proxy-bypass-list=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,127.0.0.1"
fi

if [ -n "${CHROMIUM_APP_URL:-}" ]; then
    printf "%s\n" "--app=$CHROMIUM_APP_URL"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
